postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  db: test_db
  migrations-path: file://migrations
  
redis:
  host: localhost
  port: 6379
  user:
  password:

mongo:
  host: localhost
  port: 27017
  user:
  password:
  db: test_db

http-server:
  ip: localhost
  port: 6969
  read-timeout: 5
  read-header-timeout: 4
  write-timeout: 10
  idle-timeout: 20

auth:
  secret-key: khoorshidPooshteshBeMast
  token-expiration-hours: 72 

log:
  file-name: logs.log