postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  db: test
  
redis:
  host: localhost
  port: 6379
  user:
  password: redis

mongo:
  host: localhost
  port: 27017
  user:
  password:
  db: dbsermovie

httpserver:
  ip: localhost
  port: 6969